# Generated by Django 4.1.3 on 2022-11-28 14:21

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='default_area', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Coords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('height', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='default_title', max_length=64)),
                ('image', models.ImageField(upload_to='uploads/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winter', models.CharField(choices=[('1А', '1А'), ('1Б', '1Б'), ('2А', '2А'), ('2Б', '2Б'), ('3А', '3А'), ('3Б', '3Б')], default=('1А', '1А'), max_length=2)),
                ('summer', models.CharField(choices=[('1А', '1А'), ('1Б', '1Б'), ('2А', '2А'), ('2Б', '2Б'), ('3А', '3А'), ('3Б', '3Б')], default=('1А', '1А'), max_length=2)),
                ('autumn', models.CharField(choices=[('1А', '1А'), ('1Б', '1Б'), ('2А', '2А'), ('2Б', '2Б'), ('3А', '3А'), ('3Б', '3Б')], default=('1А', '1А'), max_length=2)),
                ('spring', models.CharField(choices=[('1А', '1А'), ('1Б', '1Б'), ('2А', '2А'), ('2Б', '2Б'), ('3А', '3А'), ('3Б', '3Б')], default=('1А', '1А'), max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Pereval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beauty_title', models.CharField(default='default_beauty_title', max_length=64)),
                ('title', models.CharField(default='default_title', max_length=64)),
                ('other_titles', models.CharField(default='default', max_length=64)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('new', 'new'), ('pending', 'pending'), ('accepted', 'accepted'), ('rejected', 'rejected')], default='new', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('name', models.CharField(default='default_name', max_length=64)),
                ('family_name', models.CharField(default='default_fam', max_length=64)),
                ('patronymic', models.CharField(default='default_otc', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='PerevalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapp.image')),
                ('pereval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapp.pereval')),
            ],
        ),
        migrations.CreateModel(
            name='PerevalArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapp.area')),
                ('pereval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapp.pereval')),
            ],
        ),
        migrations.AddField(
            model_name='pereval',
            name='areas',
            field=models.ManyToManyField(through='mapp.PerevalArea', to='mapp.area'),
        ),
        migrations.AddField(
            model_name='pereval',
            name='coords',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapp.coords'),
        ),
        migrations.AddField(
            model_name='pereval',
            name='images',
            field=models.ManyToManyField(through='mapp.PerevalImage', to='mapp.image'),
        ),
        migrations.AddField(
            model_name='pereval',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mapp.user'),
        ),
    ]
