# Generated by Django 4.1.3 on 2022-12-04 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0004_alter_user_email_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pereval',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapp.user'),
        ),
    ]
